name: agentics
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11,<3.13
  - ipykernel
  - pydantic
  - python-dotenv
  - numpy
  - cvxpy
  - gymnasium
  - pytorch
  - ffmpeg
  - pip
  - mkdocs-material
  - pip:
      - crewai
      - crewai_tools
      - crewai[litellm]
      - crewai[google-genai]
      - pandas
      - matplotlib
      - mcp
      - fastmcp
      - gurobipy
      - streamlit